---
- name: Test playbook for git repository
  hosts: all
  become: yes
  tasks:

    - name: Ensure httpd is installed
      yum:
        name: httpd
        state: present
        
    - name: Ensure web service is start and enabled
      service:
        name: httpd
        state: started
        enabled: true

    - name: Ensure web page is loaded
      template:
        src: templates/index.html.j2
        dest: /home/student/
